<main class="form-signin w-25 m-auto text-center">
    <form method="POST">
        <i class="bi bi-person-circle mb-4 login-icon"></i>
        <h1 class="h3 mb-3 fw-normal">Sign Up</h1>

        <div class="form-floating mt-3">
            <input type="text" class="form-control" name="name" placeholder="Enter your name" required>
            <label for="name">Full Name</label>
        </div>
        <div class="form-floating mt-3">
            <input type="email" class="form-control" name="email" id="userEmail" placeholder="name@example.com" required>
            <label for="email">Email address</label>
        </div>
        <div class="form-floating mt-3">
            <input type="password" class="form-control" name="password" id="userPassword" placeholder="Password" required>
            <label for="password">Password</label>
        </div>
        <button class="w-100 btn btn-lg btn-primary mt-3" type="submit">Sign Up</button>
        <div class="mb-3 mt-4">
            <label>
                Already have an account <a href="/app/users/login">sign in</a>
            </label>
        </div>

    </form>
</main>
<div class="alert alert-success text-break w-50 m-auto">
    Token:<br>
    <?php if(isset($token)) {echo $token;} ?>
</div>