<h1 class="text-center text-success border-bottem">Orders Dashboard</h1>

<div class="container-fluid">
    <table class="table table-hover">
        <thead class="text-light bg-dark">
        <tr>
            <th scope="col">id</th>
            <th scope="col">Customer name</th>
            <th scope="col">Product Name</th>
            <th scope="col">Quantity</th>
            <th scope="col">Status</th>
            <th scope="col">Date</th>
        </tr>
        </thead>
        <tbody>
            <?php
            foreach ($orders as $order) {
                echo '<tr>
                        <th scope="row">'.$order->_id.'</th>
                        <td>'.$order->customer_name.'</td>
                        <td>'.$order->product_id.'</td>
                        <td>'.$order->quantity.'</td>
                        <td>'.$order->status.'</td>
                        <td>'.$order->date.'</td>
                    </tr>';
            }
            ?>
        </tbody>

    </table>
</div>