<main class="form-signin w-25 m-auto text-center">
    <form method="POST">
        <i class="bi bi-person-circle mb-4 login-icon"></i>
        <h1 class="h3 mb-3 fw-normal">Login</h1>

        <div class="form-floating mt-3">
            <input type="email" class="form-control" name="email" id="userEmail" placeholder="name@example.com" required>
            <label for="email">Email address</label>
        </div>
        <div class="form-floating mt-3">
            <input type="password" class="form-control" name="password" id="userPassword" placeholder="Password" required>
            <label for="password">Password</label>
        </div>
        <button class="w-100 btn btn-lg btn-primary mt-3" type="submit">Login</button>
        <div class="mb-3 mt-4">
            <label>
                Don't have an account <a href="/frontend/users/signup">sign up</a>
            </label>
        </div>

    </form>
</main>