<h1 class="text-center text-success border-bottem">Products Dashboard</h1>

<div class="container-fluid">
    <table class="table table-hover">
        <thead class="text-light bg-dark">
        <tr>
            <th scope="col">id</th>
            <th scope="col">Product name</th>
            <th scope="col">Category</th>
            <th scope="col">Price</th>
            <th scope="col">Stock</th>
            <th scope="col">Action</th>
        </tr>
        </thead>
        <tbody>
            <?php
            foreach ($products as $product) {
                echo '<tr>
                        <th scope="row">'.$product->_id.'</th>
                        <td>'.$product->name.'</td>
                        <td>'.$product->category.'</td>
                        <td>'.$product->price.'</td>
                        <td>'.$product->stock.'</td>
                        <td><a href="/app/product/productEdit/'.$product->_id.'" class="btn btn-sm btn-outline-warning">Edit</a></td>
                    </tr>';
            }
            ?>
        </tbody>

    </table>
</div>