<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Store-API</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <style>
        .login-icon {
            font-size: 80px;
            color: #0B5ED7;
        }
    </style>
</head>

<body>
    <div class="container-fluid">
        <div class="mt-2 text-center border-bottom pb-3 shadow mb-3">
        <?php
            if (isset($this->session->userId)){
                echo '<h2 class="text-primary d-inline">'.$this->session->userName.'</h2>';
                echo '<a href="/app/users/logout" class="mx-3 btn btn-sm btn-outline-danger">logout</a>';
            } else {
                echo '<a href="/app/users/login" class="btn btn-sm btn-outline-dark mx-1">Login</a>';
            }
            
        ?>
            <a href="/app/webHook" class="btn btn-sm btn-outline-dark mx-1">Create Web Hooks</a>
            <a href="/app/admin/orders" class="btn btn-sm btn-outline-dark mx-1">Orders</a>
            <a href="/app/admin/products" class="btn btn-sm btn-outline-dark mx-1">Products</a>
        </div>
        <?php echo $this->getContent(); ?>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>

</html>